name: bat_foundation
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_bloc: ^8.1.3
  country_picker: ^2.0.20
  persistent_bottom_nav_bar: ^5.0.2
  bloc: ^8.1.1
  equatable: ^2.0.5
  dio: ^5.3.2
  logger: ^1.3.0
  meta: ^1.9.1
  iconsax: ^0.0.8
  carousel_slider: ^4.1.1
  path_provider: ^2.0.15
  flutter_native_splash: ^2.3.1
  shared_preferences: ^2.1.1
  searchfield: ^0.8.3
  simple_gradient_text: ^1.2.4
  flutter_spinkit: ^5.2.0
  internet_connection_checker: ^1.0.0+1
  hydrated_bloc: ^9.1.2
  json_serializable: ^6.7.0
  clay_containers: ^0.3.2
  rflutter_alert: ^2.0.7
  flutter_switch: ^0.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.6
  build_runner: ^2.4.6
  uuid: ^3.0.7
  smooth_page_indicator: ^1.1.0
  dropdown_textfield: ^1.0.8
  intl: ^0.18.1
  dartz: ^0.10.1
  lottie: ^2.5.0
  expandable_page_view: ^1.0.17
  anim_search_bar: ^2.0.3
  get: ^4.6.5
  get_it: ^7.2.0
  cached_video_player: ^2.0.4
  cached_network_image:
  video_player:
  wakelock: ^0.6.2
  font_awesome_flutter: ^10.5.0
  shimmer: ^2.0.0
  jiffy: ^5.0.0
  clean_dialog: ^0.0.16
  another_flushbar: 1.10.28

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  android_12:
  android: true
  android_gravity: center
  ios_content_mode: center
  ios: true
  fullscreen: true

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
